name: Run Selenium Test with x64 Intel MacOS Big Sur Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    # Specify the macOS runner version matching your Big Sur environment
    runs-on: macos-11  # This specifies using macOS 11 (Big Sur), which is Intel-based x64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace with the preferred Python version

      - name: Use Local ChromeDriver
        run: |
          mkdir -p $HOME/.chromedriver
          cp /Users/somud/Downloads/chromedriver-mac-x64\ 2/chromedriver $HOME/.chromedriver/chromedriver
          chmod +x $HOME/.chromedriver/chromedriver
          sudo mv $HOME/.chromedriver/chromedriver /usr/local/bin/chromedriver

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Run Selenium Test
        run: python your_test_file.py  # Replace with your test script filename
