name: Run Selenium Test with ChromeDriver

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Replace with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Download ChromeDriver
        run: |
          curl -O https://chromedriver.storage.googleapis.com/130.0.6723.69/chromedriver_mac64.zip
          unzip chromedriver_mac64.zip -d $HOME/.chromedriver
          sudo mv $HOME/.chromedriver/chromedriver /usr/local/bin/chromedriver

      - name: Run Selenium Test
        run: python your_test_file.py # Replace with the name of your test scr
